### ISSUE TITLE
Switch Transactional Mail Provider

### ISSUE THREAD

**Issue by jseppi** [TNRIS/contact-app#23]
Mandrill is becoming a pay-service only: http://blog.mailchimp.com/important-changes-to-mandrill/

We need to switch to another transactional mail service. Amazon SES looks promising. Mailgun is another option with a free tier.

**Comment by yepher** [comment]
Just incase it can help here is the Mandrill migration to SparkPost [guide](https://www.sparkpost.com/mandrill-migration-guide) and this [Slack channel](http://slack.sparkpost.com) is available if you need help with the migration.
