### ISSUE TITLE
Maybe don't cc everything to tnris-data-support

### ISSUE THREAD

**Issue by jseppi** [TNRIS/contact-app#6]
talk with @mitchellryant about this.
we might want to make another email config option to not cc tnris-data-support for some contact forms

**Comment by jseppi** [comment]
This is fixed in https://github.com/TNRIS/contact-app/commit/1f5891525c1cd17f2f8f83de18b9193ecbbe8a0b by making "cc" a config option

**Comment by wilsaj** [comment]
This was sort of by design. Do we ever want to **not** log form submissions in the ticket system?

**Comment by jseppi** [comment]
@mitchellryant didn't seem to like everything getting cc'd to tickets.
Though he also expressed desire to have ALL communication go through the ticketing system, but that would require some training for other users to not use their personal email accounts (such as for the google imagery request forms).

**Comment by mitchellryant** [comment]
I would like all the forms to go through osTickets, and Gayla/Felicia to use only osTickets to respond.

**Comment by wilsaj** [comment]
Yeah, I think forcing a cc to the ticket email is a good idea if only to keep a record of the contact. Maybe a better way to articulate that intent in the config is to add an `always_include` variable that gets appended to the `cc` list if it isn't already somewhere in `to` or `cc`.

**Comment by wilsaj** [comment]
Per discussions with @mitchellryant - we actually are now *only* emailing to the data support email. Still leaving in code that supports other to/cc's since it might be used later and is handy for debugging, etc.
